
[project]
name = "repl-nix-video-frames-extractor"
version = "0.1.0"
description = "Video frame extractor web application"
requires-python = ">=3.12"
dependencies = [
    "flask",
    "opencv-python-headless",
    "imutils",
    "fire"
]
